A/A/A/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first.urls',namespace='first')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
]

A/A/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('reset/', views.UserPassReset.as_view(), name='reset_pass'),
    path('reset/done/', views.PasswordResetDone.as_view(),name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),name='password_reset_confirm'),
    path('confirm/done/',views.PasswordResetComplete.as_view(),name='password_reset_complete')
]

A/A/first/urls.py
from django.urls import path
from . import views

app_name = 'first'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('create/', views.TodoCreate.as_view(), name='create_todo'),
    path('<slug:myslug>', views.DetailTodo.as_view(), name='detail_todo'),
    path('delete/<int:pk>/', views.DeleteTodo.as_view(), name='delete_todo'),
    path('update/<int:pk>/', views.UpdateTodo.as_view(), name='update_todo'),
    path('<int:year>/<int:month>/',views.MonthTodo.as_view(),name='month_todo'),
]

A/A/accounts/models.py
from django.db import models

# Create your models here.

A/A/first/models.py
from django.db import models

class Todo(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(blank=True,null=True)

    def __str__(self):
        return f'{self.title}' 
    
class Comment(models.Model):
    todo = models.ForeignKey(Todo,on_delete=models.CASCADE,related_name='tcomments')
    name = models.CharField(max_length=200)
    body = models.TextField()
    def __str__(self):
        return self.name

A/A/first/forms.py
from django import forms
from django.db import models
from django.db.models import fields
from .models import Comment

class TodoCreateForm(forms.Form):
    title = forms.CharField(max_length=200)

class TodoCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','body')

A/A/accounts/views.py
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class UserLogin(auth_views.LoginView):
    template_name = 'accounts/login.html'
    extra_context = {'name': 'soheil'}


class UserPassReset(auth_views.PasswordResetView):
    email_template_name = 'accounts/password_reset_email.html'
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(auth_views.PasswordResetDoneView):
    template_name = 'accounts/reset_done.html'

class PasswordResetConfirm(auth_views.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')

class PasswordResetComplete(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

A/A/first/views.py
from django.shortcuts import render
#from django.views import View

from django.views.generic.base import TemplateView
from .models import Comment, Todo

from django.views.generic.list import ListView

from django.views.generic.detail import DetailView

from django.views.generic.edit import FormView
from .forms import TodoCreateForm
from django.urls import reverse_lazy,reverse
from django.utils.text import slugify
from django.contrib import messages

from django.views.generic.edit import CreateView

from django.views.generic.edit import DeleteView

from django.views.generic.edit import UpdateView

from django.views.generic.dates import MonthArchiveView

from django.contrib.auth.mixins import LoginRequiredMixin

from django.views.generic.edit import FormMixin
from .forms import TodoCommentForm

#from A.first import models

# class Home(View):
#     template_name = "first/home.html"
#     context = {'name':'Soheil'}
#     def get(self,request,*args,**kwargs):
#         return render (request,self.template_name,self.context)

# class Home(TemplateView):
#     template_name = "first/home.html"
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["todos"] = Todo.objects.all()
#         return context


class Home(ListView):
    #model = Todo
    context_object_name = 'todos' #object_list
    template_name = 'first/home.html' #first/todo_list.html
    ordering = ['-created']
    #queryset = Todo.objects.all()
    def get_queryset(self):
        return Todo.objects.all()

#class DetailTodo(DetailView):
#     model = Todo
#     slug_field = 'slug'
#     slug_url_kwarg = 'myslug'
    
# class DetailTodo(DetailView):
#     slug_field = 'slug'
#     slug_url_kwarg = 'myslug'

#     def get_queryset(self,**kwargs):
#         if self.request.user.is_authenticated:
#             return Todo.objects.filter(slug=self.kwargs['myslug'])
#         else:
#             return Todo.objects.none()


class DetailTodo(LoginRequiredMixin,FormMixin,DetailView):
    model = Todo
    form_class = TodoCommentForm
    slug_field = 'slug'
    slug_url_kwarg = 'myslug'

    def get_success_url(self):
        return reverse('first:detail_todo',kwargs={'myslug':self.object.slug})

    def post(self,request,*args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            comment = Comment(todo = self.object,name=form.cleaned_data['name'],body=form.cleaned_data['body'])
            comment.save()
        return super().form_valid(form)

# class TodoCreate(FormView):
#     form_class = TodoCreateForm
#     template_name = 'first/todo_create.html'
#     success_url = reverse_lazy('first:home')

#     def form_valid(self,form):
#         self.create_todo(form.cleaned_data)
#         return super().form_valid(form)

#     def create_todo(self,data):
#         todo = Todo(title=data['title'],slug=slugify(data['title']))
#         todo.save()
#         messages.success(self.request,'your todo saved','success')

class TodoCreate(CreateView):
    model = Todo
    fields = ('title',)
    template_name = 'first/todo_create.html'
    success_url = reverse_lazy('first:home')

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.slug = slugify(form.cleaned_data['title'])
        todo.save()
        messages.success(self.request,'your todo saved','success')
        return super().form_valid(form)

class DeleteTodo(DeleteView):
    model = Todo
    template_name = "first/todo_delete.html"
    success_url = reverse_lazy('first:home')

class UpdateTodo(UpdateView):
    model = Todo
    fields = ('title',)
    template_name = "first/todo_update.html"
    success_url = reverse_lazy('first:home')

class MonthTodo(MonthArchiveView):
    model = Todo
    date_field = 'created'
    month_format = '%m'
    template_name = 'first/todo_month.html'

A/A/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" class="mt-3">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock %}

A/A/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
    <h3>your password reset successfully now login</h3>
{% endblock %}

A/A/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
    {% if validlink %}
        <h3>New Password</h3>
        <form action="" method="post" class="mt-3">
            {% csrf_token %}
            {{ form }}
            <button type="submit" class="btn btn-dark">Submit</button>
        </form>
    {% else %}
        <h3>thid link is not valid</h3>
    {% endif %}
{% endblock %}

A/A/accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

A/A/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block content %}
    <h3>Reset Password</h3>
    <form action="" method="post" class="mt-3">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock %}

A/A/accounts/templates/accounts/reset_done.html
{% extends 'base.html' %}

{% block content %}
    <h3>Reset Password Link send to your email</h3>
{% endblock %}

A/A/first/templates/first/home.html
{% extends 'base.html' %}

{% block content %}
    <h2>Hi</h2>
    <hr>
    <ul>
        {% for todo in todos %}
        <li class="mb-3">
            <a class="btn" href="{% url 'first:detail_todo' todo.slug %}">{{ todo.title }}</a>
            <a class="btn btn-info mx-3" href="{% url 'first:update_todo' todo.id %}">Update</a>
            <a class="btn btn-warning" href="{% url 'first:delete_todo' todo.id %}">Delete</a>
        </li>
        {% endfor %}
    </ul>
{% endblock %}

A/A/first/templates/first/todo_create.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-dark">Submit</button>
    </form>
{% endblock %}

A/A/first/templates/first/todo_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <p>are you sure want to delete <b>{{ object }}</b> ?</p>
        <button class="btn btn-dark" type="submit">submit</button>
    </form>
{% endblock %}

A/A/first/templates/first/todo_detail.html
{% extends 'base.html' %}

{% block content %}
    <small>{{ object.created }}</small>
    <h2>{{ object.title }}</h2>
    <hr>
    <form action="" method="post" class="mt-3">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-dark" type="submit">submit</button>
    </form>
    <hr>
    {% for cmt in object.tcomments.all %}
        <small>{{ cmt.name }}</small>
        <p>{{ cmt.body }}</p>
    {% endfor %}
{% endblock %}

A/A/first/templates/first/todo_month.html
{% extends 'base.html' %}

{% block content %}
<ul class="mt-3">
    {% for todo in object_list %}
    <li><h5>{{ todo }}</h5></li>
    {% endfor %}
</ul>
{% endblock %}

A/A/first/templates/first/todo_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post" class="mt-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-dark" type="submit">submit</button>
    </form>
{% endblock %}

A/A/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <title>Class Base Course</title>
</head>
<body>
    {% include 'inc/navbar.html' %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                {% include 'inc/messages.html' %}
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

A/A/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
    <div class="alert alert-{{ msg.tags }}" role="alert">
        {{ msg }}
    </div>
    {% endfor %}
{% endif %}

A/A/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first:home' %}">Home</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'first:create_todo' %}">Create Todo</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>